#' Send a Single Request to the Anthropic API
#'
#' This function sends a single prompt to the Anthropic API for message
#' completion. It handles retries in case of request failures and returns the
#' response content.
#'
#' @param prompt A list containing the prompt messages, created using a specific
#'   format understood by the Anthropic API, e.g., `list(list(role = "user",
#'   content = "hello world"))`.
#' @param model The model to be used for generating the response, such as
#'   "claude-3-haiku".
#' @param n_candidates The number of response candidates to generate. Defaults
#'   to 1.
#' @param max_retries An integer specifying the maximum number of retry attempts
#'   in case of request failures. Defaults to 10.
#' @param temperature A numeric value controlling the randomness of the model's
#'   output. A higher value makes the output more random. Defaults to 0.2.
#' @param max_tokens The maximum number of tokens to generate for the response.
#'   Defaults to 300.
#' @param json_mode A logical value indicating whether to process any json
#'   generated by the response. Defaults to `FALSE`.
#' @param system A character string providing additional context or instructions
#'   for the system. Defaults to `NULL`.
#' @param response_validation_fun A function to validate the response content.
#'   If not provided, the default validation function is used.
#' @param content_extraction_fun A function to extract the content from the
#'   response. If not provided, a default extraction function is used based on
#'   `json_mode`.
#' @param pause_cap A numeric value representing the maximum pause duration (in
#'   seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress
#'   messages during retries. Defaults to `FALSE`.
#'
#' @return A tibble containing the response content and usage details, including
#'   prompt and response tokens.
#' @export
claude_single_request <- function(prompt,
                                  model,
                                  n_candidates = 1,
                                  max_retries = 10,
                                  temperature = 0.2,
                                  max_tokens = 300,
                                  json_mode = FALSE,
                                  system = NULL,
                                  response_validation_fun,
                                  content_extraction_fun,
                                  pause_cap = 1200,
                                  quiet = FALSE) {

  body <- jsonlite::toJSON(
    list(
      messages = prompt,
      model = model,
      max_tokens = max_tokens,
      temperature = temperature
    ),
    auto_unbox = TRUE,
    pretty = TRUE
  )

  res <- httr::RETRY(
    verb = "POST",
    url = "https://api.anthropic.com/v1/messages",
    config = httr::add_headers("x-api-key" = Sys.getenv("ANTHROPIC_API_KEY"),
                               "anthropic-version" = "2023-06-01",
                               "system" = system,
                               "content-type" = "application/json"),
    body = body,
    encode = "json",
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  httr::stop_for_status(res)
  response <- httr::content(res)

  df <- claude_usage(response)
  if (missing(content_extraction_fun)) {
    if(!json_mode) {
      content_extraction_fun <- get("claude_default_content_extraction")
    } else {
      content_extraction_fun <- get("claude_json_content_extraction")
    }
  }

  content <- do.call(content_extraction_fun, list(response))
  df <- df |>
    dplyr::mutate(response = list(content))

  df
}

claude_default_response_validation <- function(response) {
  return(TRUE)
}

claude_json_response_validation <- function(response) {
  httr::content(response) |>
    claude_default_content_extraction() |>
    default_json_content_cleaning() |>
    jsonlite::validate()
}

claude_default_content_extraction <- function(response_content) {
  response_content$content[[1]]$text
}

claude_json_content_extraction <- function(response_content) {
  response_content |>
    claude_default_content_extraction() |>
    default_json_content_extraction()
}

claude_usage <- function(response) {
  response$usage |>
    dplyr::as_tibble() |>
    dplyr::mutate(model = response$model)
}

