#' Format Prompts for Mistral Batch API
#'
#' This function transforms a list of prompts into the appropriate JSONL format required for
#' the Mistral Batch API.
#'
#' @param prompts A list of prompts with each prompt containing a list of messages (role and content).
#' @param max_tokens Max number of tokens for each response. Defaults to 100.
#'
#' @return A character string formatted in JSONL, ready to be saved to a file.
#' @export
mistral_format_prompts_for_batch <- function(prompts, max_tokens = 100) {
  json_lines <- lapply(names(prompts), function(name) {
    list(
      custom_id = name,
      body = list(
        max_tokens = max_tokens,
        messages = prompts[[name]]
      )
    )
  })
  jsonl_string <- paste(sapply(json_lines, jsonlite::toJSON, auto_unbox = TRUE), collapse = "\n")
  jsonl_string
}

#' Upload JSONL File to Mistral for Batch Processing
#'
#' This function uploads a JSONL file to Mistral for batch processing using the Files API.
#'
#' @param jsonl The JSONL string generated by [mistral_format_prompts_for_batch()].
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A list containing the response details, including the file ID.
#' @export
mistral_upload_batch_file <- function(jsonl, max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  tmp_file <- fs::file_temp(ext = "jsonl")
  writeLines(jsonl, tmp_file)

  res <- httr::RETRY(
    verb = "POST",
    url = "https://api.mistral.ai/v1/files",
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY")),
      "Content-Type" = "multipart/form-data"
    ),
    body = list(
      file = httr::upload_file(tmp_file),
      purpose = "batch"
    ),
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response <- httr::content(res)

  # Return the response details
  response
}

#' Create Mistral Batch Job
#'
#' This function creates a batch request using the uploaded file ID from the Mistral Batch API.
#'
#' @param upload_response The response object returned by [mistral_upload_batch_file()] containing the uploaded file ID.
#' @param model The model to use for processing the batch (e.g., "mistral-small-latest").
#' @param endpoint The endpoint for processing each request in the batch, e.g., "/v1/chat/completions".
#' @param metadata Optional custom metadata for the batch.
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A list containing the response details, including batch ID and status.
#' @export
mistral_create_batch_job <- function(upload_response, model, endpoint = "/v1/chat/completions", metadata = NULL,
                                     max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  file_id <- upload_response$id

  body <- jsonlite::toJSON(
    list(
      model = model,
      input_files = list(file_id),
      endpoint = endpoint,
      metadata = metadata
    ),
    auto_unbox = TRUE,
    pretty = TRUE
  )

  res <- httr::RETRY(
    verb = "POST",
    url = "https://api.mistral.ai/v1/batch/jobs",
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY")),
      "Content-Type" = "application/json"
    ),
    body = body,
    encode = "json",
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response <- httr::content(res)

  # Return the response details
  response
}

#' Check Status of Mistral Batch Job
#'
#' This function checks the status of an existing batch request using the Mistral Batch API.
#'
#' @param job_id The batch job ID to check the status for.
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A list containing the current status of the batch.
#' @export
mistral_check_batch_status <- function(job_id, max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  url <- paste0("https://api.mistral.ai/v1/batch/jobs/", job_id)

  res <- httr::RETRY(
    verb = "GET",
    url = url,
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY")),
      "Content-Type" = "application/json"
    ),
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response <- httr::content(res)

  # Return the response details
  response
}

#' Download Results of Mistral Batch Job
#'
#' This function downloads the results of a completed batch request using the output file ID from the Mistral Batch API.
#'
#' @param output_file_id The output file ID to download the results for.
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A character vector containing each line of the .jsonl result file.
#' @export
mistral_download_batch_results <- function(output_file_id, max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  url <- paste0("https://api.mistral.ai/v1/files/", output_file_id, "/content")

  res <- httr::RETRY(
    verb = "GET",
    url = url,
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY"))
    ),
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response_content <- httr::content(res, as = "text")

  response_content
}

#' Cancel Mistral Batch Job
#'
#' This function cancels an ongoing batch request using the Mistral Batch API.
#'
#' @param job_id The batch job ID to cancel.
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A list containing the response details after the cancel request is submitted.
#' @export
mistral_cancel_batch_job <- function(job_id, max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  url <- paste0("https://api.mistral.ai/v1/batch/jobs/", job_id, "/cancel")

  res <- httr::RETRY(
    verb = "POST",
    url = url,
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY")),
      "Content-Type" = "application/json"
    ),
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response <- httr::content(res)

  # Return the response details
  response
}

#' List Mistral Batch Jobs
#'
#' This function lists all the batch jobs being processed for a user using the Mistral Batch API.
#'
#' @param status An optional filter to specify the status of jobs to return. Defaults to NULL (returns all statuses).
#' @param limit An integer specifying the maximum number of batches to return. Defaults to 10.
#' @param max_retries An integer indicating the maximum number of retry attempts in case of request failures. Defaults to 3.
#' @param pause_cap A numeric value representing the maximum pause duration (in seconds) between retries. Defaults to 1200.
#' @param quiet A logical value indicating whether the function should suppress messages during retries. Defaults to `FALSE`.
#'
#' @return A list containing the details of the batches.
#' @export
mistral_list_batches <- function(status = NULL, limit = 10, max_retries = 3, pause_cap = 1200, quiet = FALSE) {
  url <- "https://api.mistral.ai/v1/batch/jobs"
  if (!is.null(status)) {
    url <- paste0(url, "?status=", status)
  }
  url <- paste0(url, "&limit=", limit)

  res <- httr::RETRY(
    verb = "GET",
    url = url,
    config = httr::add_headers(
      "Authorization" = paste("Bearer", Sys.getenv("MISTRAL_API_KEY")),
      "Content-Type" = "application/json"
    ),
    times = max_retries,
    pause_base = 1,
    pause_cap = pause_cap,
    quiet = quiet
  )

  # Check if the response contains an error
  httr::stop_for_status(res)
  response <- httr::content(res)

  # Return the response details
  response
}

#' Execute Mistral Batch Workflow
#'
#' This function orchestrates the entire Mistral batch process: it formats the prompts, uploads the batch file, creates the batch job, and polls until the results are ready.
#'
#' @param prompts A list of prompts, each containing messages to send to the model.
#' @param model The model to use for processing the prompts, e.g., "mistral-small-latest". If not specified, the function will use a default model.
#' @param timeout A numeric value representing the time (in seconds) to wait between polling attempts. Defaults to 3600 seconds (1 hour).
#' @param max_tokens The maximum number of tokens to generate for each response. Defaults to 100.
#' @param quiet A logical value indicating whether the function should suppress messages during the process. Defaults to `FALSE`.
#'
#' @return A character vector containing each line of the .jsonl result file.
#' @export
mistral_batch <- function(prompts, model, timeout = 3600, max_tokens = 100, quiet = FALSE) {
  jsonl <- mistral_format_prompts_for_batch(prompts, max_tokens = max_tokens)
  batch_file <- mistral_upload_batch_file(jsonl = jsonl, quiet = quiet)
  batch_job <- mistral_create_batch_job(batch_file, model = model, quiet = quiet)

  repeat {
    status_response <- mistral_check_batch_status(batch_job$id, quiet = quiet)
    processing_status <- status_response$status
    output_file_id <- status_response$output_file_id

    if (processing_status == "SUCCESS" && !is.null(output_file_id)) {
      message("Batch processing completed. Retrieving results...")
      results <- mistral_download_batch_results(output_file_id, quiet = quiet)
      return(results)
    } else if (processing_status %in% c("QUEUED", "RUNNING")) {
      message(glue::glue("{lubridate::now()}: Batch still in progress. Waiting for {timeout} seconds before next poll..."))
      Sys.sleep(timeout)
    } else {
      stop("Batch job ", processing_status, ".")
    }
  }
}

#' Submit Mistral Batch Job
#'
#' This function submits a batch job to Mistral, which processes multiple prompts
#' concurrently using the specified model. It formats the prompts, uploads the
#' batch file, and creates the batch request.
#'
#' @param prompts A list of prompts, each containing messages to send to the
#'   model, typically generated by [build_prompts_from_files()]. The prompts
#'   should be structured in a format suitable for Mistral's API.
#' @param model The model to use for processing the prompts (e.g.,
#'   "mistral-small-latest").
#' @param max_tokens An integer specifying the maximum number of tokens to
#'   generate for each response. Defaults to 300.
#' @param quiet A logical value indicating whether to suppress messages during
#'   the process. Defaults to FALSE.
#'
#' @return A list containing the batch job details, including the batch ID and
#'   other metadata. The status of the job can be checked using
#'   [mistral_check_batch_status()].
#' @export
mistral_batch_job <- function(prompts, model, max_tokens = 300, quiet = FALSE) {
  checkmate::assert_class(prompts, "mistral")
  jsonl <- mistral_format_prompts_for_batch(prompts, max_tokens = max_tokens)
  batch_file <- mistral_upload_batch_file(jsonl = jsonl, quiet = quiet)
  batch_job <- mistral_create_batch_job(batch_file, model = model, quiet = quiet)
  batch_job
}
